# Compiler and flags
CC = cc68x
AS = gen
CFLAGS = -g -c
LDFLAGS = -g

# Source files and objects
SRCS = tst_rast.c raster.c 
OBJS = tst_rast.o raster.o 
EXEC = tst_rast

# Default target
all: $(EXEC)

# Linking
$(EXEC): $(OBJS)
	$(CC) $(LDFLAGS) $(OBJS) -o $(EXEC)

# Compiling C files
tst_rast.o: tst_rast.c raster.h
	$(CC) $(CFLAGS) -o tst_rast.o tst_rast.c

raster.o: raster.c raster.h
	$(CC) $(CFLAGS) -o raster.o raster.c


# Clean rule
clean:
	ls raster.o



