# Compiler and flags
CC = cc68x
AS = gen
CFLAGS = -g -c
LDFLAGS = -g
RM = rm

# Folders
STAGE2 = stage2
STAGE3 = stage3

# Source files and objects
SRCS = $(STAGE2)/tst_rast.c $(STAGE2)/raster.c $(STAGE3)/model.c
OBJS = tst_rast.o raster.o model.o
EXEC = tst_rast

# Default target
all: $(EXEC)

# Linking
$(EXEC): $(OBJS)
	$(CC) $(LDFLAGS) $(OBJS) -o $(EXEC)

# Compiling C files
tst_rast.o: $(STAGE2)/tst_rast.c $(STAGE2)/raster.h $(STAGE3)/model.h
	$(CC) $(CFLAGS) -o tst_rast.o $(STAGE2)/tst_rast.c

raster.o: $(STAGE2)/raster.c $(STAGE2)/raster.h
	$(CC) $(CFLAGS) -o raster.o $(STAGE2)/raster.c

model.o: $(STAGE3)/model.c $(STAGE3)/model.h
	$(CC) $(CFLAGS) -o model.o $(STAGE3)/model.c

# Clean rule
clean:
	$(RM) -f *.o $(OBJS) $(EXEC)
