# Compiler and flags
CC = cc68x
AS = gen
CFLAGS = -g -c
LDFLAGS = -g
RM = rm

# Source files and objects
SRCS = tst_rast.c raster.c model.c
OBJS = tst_rast.o raster.o model.o
EXEC = tst_rast

# Default target
all: $(EXEC)

# Linking
$(EXEC): $(OBJS)
	$(CC) $(LDFLAGS) $(OBJS) -o $(EXEC)

# Compiling C files
tst_rast.o: tst_rast.c raster.h
	$(CC) $(CFLAGS) -o tst_rast.o tst_rast.c

raster.o: raster.c raster.h
	$(CC) $(CFLAGS) -o raster.o raster.c

model.o: model.c model.h
	$(CC) $(CFLAGS) -o model.o model.c


# Clean rule
clean:
	$(RM) -f *.o $(OBJS) $(EXEC)



